"""empty message

Revision ID: 043cb91b5159
Revises: 9ecebcac35e6
Create Date: 2020-05-20 16:49:27.353660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043cb91b5159'
down_revision = '9ecebcac35e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('subject', sa.String(length=15), nullable=True),
    sa.Column('date_of_post', sa.DateTime(), nullable=True),
    sa.Column('post', sa.Text(), nullable=False),
    sa.Column('poster', sa.String(length=30), nullable=False),
    sa.Column('read', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogpost')
    # ### end Alembic commands ###
