"""empty message

Revision ID: 2cea7a738680
Revises: bfe600779034
Create Date: 2020-05-18 10:30:45.090964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cea7a738680'
down_revision = 'bfe600779034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('acc_numbers', sa.String(length=15), nullable=False))
    op.drop_column('withdrawals', 'acc_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('acc_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('withdrawals', 'acc_numbers')
    # ### end Alembic commands ###
