"""empty message

Revision ID: 2ddce84ec6eb
Revises: 7dd5653f28e1
Create Date: 2020-05-10 09:54:25.373932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ddce84ec6eb'
down_revision = '7dd5653f28e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picked_post', sa.Column('web_link', sa.String(length=40), nullable=False))
    op.drop_column('picked_post', 'short_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picked_post', sa.Column('short_link', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('picked_post', 'web_link')
    # ### end Alembic commands ###
