"""empty message

Revision ID: 46ade3f5c94a
Revises: 5db3b6aecd3a
Create Date: 2020-05-15 20:42:58.323882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ade3f5c94a'
down_revision = '5db3b6aecd3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('plan_id_code', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'plan_id_code')
    # ### end Alembic commands ###
