"""empty message

Revision ID: 50ffb1db8957
Revises: 669fb56364cc
Create Date: 2020-05-10 11:26:59.692823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ffb1db8957'
down_revision = '669fb56364cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picked_post', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picked_post', 'description')
    # ### end Alembic commands ###
