"""empty message

Revision ID: 53ef20b8a881
Revises: de122a36b492
Create Date: 2020-05-18 10:29:14.010579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ef20b8a881'
down_revision = 'de122a36b492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('acc_numbers', sa.String(length=15), nullable=True))
    op.drop_column('user', 'acc_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('acc_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'acc_numbers')
    # ### end Alembic commands ###
