"""empty message

Revision ID: 5db3b6aecd3a
Revises: 335bff02f34b
Create Date: 2020-05-13 14:13:53.485688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db3b6aecd3a'
down_revision = '335bff02f34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ad_earning', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ad_earning')
    # ### end Alembic commands ###
