"""empty message

Revision ID: 604962958320
Revises: 79149ec77568
Create Date: 2020-05-10 09:24:59.597988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604962958320'
down_revision = '79149ec77568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ad_collected_day', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ad_collected_day')
    # ### end Alembic commands ###
