"""empty message

Revision ID: 6d33923ec73b
Revises: df848bc9376f
Create Date: 2020-05-17 06:30:45.490476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d33923ec73b'
down_revision = 'df848bc9376f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('balance_id_code', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'balance_id_code')
    # ### end Alembic commands ###
