"""empty message

Revision ID: 737d5c3396b3
Revises: ff46dc1e4177
Create Date: 2020-05-18 10:37:47.917771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737d5c3396b3'
down_revision = 'ff46dc1e4177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('acc_number', sa.String(length=15), nullable=False))
    op.drop_column('withdrawals', 'acc_numberss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('acc_numberss', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('withdrawals', 'acc_number')
    # ### end Alembic commands ###
