"""empty message

Revision ID: 79149ec77568
Revises: 9c793962da05
Create Date: 2020-04-14 16:21:51.861353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79149ec77568'
down_revision = '9c793962da05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'read',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.add_column('post', sa.Column('report', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'report')
    op.alter_column('contact', 'read',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    # ### end Alembic commands ###
