"""empty message

Revision ID: 7dd5653f28e1
Revises: 604962958320
Create Date: 2020-05-10 09:44:46.374850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7dd5653f28e1'
down_revision = '604962958320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ad_collected_date', sa.String(length=12), nullable=True))
    op.drop_column('user', 'ad_collected_day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ad_collected_day', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'ad_collected_date')
    # ### end Alembic commands ###
