"""empty message

Revision ID: bd0550961730
Revises: 0e4f31d27fcd
Create Date: 2020-06-04 14:56:33.687836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0550961730'
down_revision = '0e4f31d27fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picked_post', sa.Column('plan_when_applied', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picked_post', 'plan_when_applied')
    # ### end Alembic commands ###
