"""empty message

Revision ID: bfe600779034
Revises: 53ef20b8a881
Create Date: 2020-05-18 10:29:32.402354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe600779034'
down_revision = '53ef20b8a881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('acc_number', sa.String(length=15), nullable=True))
    op.drop_column('user', 'acc_numbers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('acc_numbers', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('user', 'acc_number')
    # ### end Alembic commands ###
