"""empty message

Revision ID: d0296de2e52e
Revises: 043cb91b5159
Create Date: 2020-05-20 17:03:44.755780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0296de2e52e'
down_revision = '043cb91b5159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('image', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogpost', 'image')
    # ### end Alembic commands ###
