"""empty message

Revision ID: de122a36b492
Revises: e1bcff6fe9c0
Create Date: 2020-05-18 09:06:34.365846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de122a36b492'
down_revision = 'e1bcff6fe9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid_of_user', sa.String(length=10), nullable=False),
    sa.Column('bank_name', sa.String(length=90), nullable=False),
    sa.Column('acc_number', sa.Integer(), nullable=False),
    sa.Column('acc_name', sa.String(length=70), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawals')
    # ### end Alembic commands ###
