"""empty message

Revision ID: df848bc9376f
Revises: 46ade3f5c94a
Create Date: 2020-05-15 21:03:40.231405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df848bc9376f'
down_revision = '46ade3f5c94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refer_earning', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refer_earning')
    # ### end Alembic commands ###
