"""empty message

Revision ID: e1bcff6fe9c0
Revises: 6d33923ec73b
Create Date: 2020-05-17 06:34:28.219517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1bcff6fe9c0'
down_revision = '6d33923ec73b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verify_id_code', sa.String(length=16), nullable=True))
    op.drop_column('user', 'plan_id_code')
    op.drop_column('user', 'balance_id_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('balance_id_code', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('plan_id_code', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.drop_column('user', 'verify_id_code')
    # ### end Alembic commands ###
