"""empty message

Revision ID: ff46dc1e4177
Revises: 2cea7a738680
Create Date: 2020-05-18 10:36:38.567719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff46dc1e4177'
down_revision = '2cea7a738680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('acc_numberss', sa.String(length=15), nullable=True))
    op.drop_column('withdrawals', 'acc_numbers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('acc_numbers', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_column('withdrawals', 'acc_numberss')
    # ### end Alembic commands ###
